import { useState, useEffect } from "react";

const T = {
  bg:"#000000",raised:"#0D0D0D",surface:"#141414",subtle:"#1A1A1A",
  border:"#2A2A2A",borderHover:"#3D3D3D",
  text:"#F5F5F5",textSec:"rgba(255,255,255,0.68)",textMuted:"rgba(255,255,255,0.44)",textFaint:"rgba(255,255,255,0.24)",
  accent:"#6366F1",accentDim:"rgba(99,102,241,0.12)",brand:"#6366F1",brandLight:"#A5B4FC",
  success:"#34D399",warning:"#FBBF24",error:"#EF4444",
  mono:"'Geist Mono',ui-monospace,monospace",
  sans:"'Suisse Intl','SuisseIntl','Inter',-apple-system,system-ui,sans-serif",
  brandFont:"'TheFold Brand','Suisse Intl','Inter',-apple-system,system-ui,sans-serif",
  r:8,
};
const SW=255,SWC=56,CW=1636,IW=1232,HH=64,SP=(CW-IW)/2;

function PC(){const c=T.border,a={position:"absolute",background:c,zIndex:2,pointerEvents:"none"};return(<><div style={{...a,top:0,left:0,width:5,height:1}}/><div style={{...a,top:1,left:0,width:3,height:1}}/><div style={{...a,top:2,left:0,width:1,height:1}}/><div style={{...a,top:0,left:0,width:1,height:5}}/><div style={{...a,top:0,left:1,width:1,height:3}}/><div style={{...a,top:0,left:2,width:1,height:1}}/><div style={{...a,top:2,left:2,width:1,height:1}}/><div style={{...a,top:0,right:0,width:5,height:1}}/><div style={{...a,top:1,right:0,width:2,height:1}}/><div style={{...a,top:0,right:0,width:1,height:5}}/><div style={{...a,top:0,right:1,width:1,height:3}}/><div style={{...a,bottom:0,left:0,width:5,height:1}}/><div style={{...a,bottom:1,left:0,width:2,height:1}}/><div style={{...a,bottom:0,left:0,width:1,height:5}}/><div style={{...a,bottom:0,left:1,width:1,height:3}}/><div style={{...a,bottom:0,right:0,width:5,height:1}}/><div style={{...a,bottom:1,right:0,width:3,height:1}}/><div style={{...a,bottom:0,right:0,width:1,height:5}}/><div style={{...a,bottom:0,right:1,width:1,height:3}}/></>);}

function RI({size=16,color}){const c=color||T.textSec;return(<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={c} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="2" x2="12" y2="6"/><circle cx="12" cy="2" r="1" fill={c} stroke="none"/><rect x="4" y="6" width="16" height="12" rx="2"/><circle cx="9" cy="12" r="1.5" fill={c} stroke="none"/><circle cx="15" cy="12" r="1.5" fill={c} stroke="none"/><line x1="9" y1="16" x2="15" y2="16"/></svg>);}
function CI({color,size=12}){return(<svg width={size} height={size} viewBox="0 0 12 12" fill="none"><path d="M2.5 6L5 8.5L9.5 3.5" stroke={color||T.textMuted} strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/></svg>);}
function BellIcon(){return(<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M10 12a2 2 0 01-4 0M3.5 6.5a4.5 4.5 0 019 0c0 3.5 1.5 4.5 1.5 4.5H2s1.5-1 1.5-4.5z"/></svg>);}

function NotifBell({onGoTask}){const[open,setOpen]=useState(false);
const alerts=[{id:"T-003",title:"Database migrasjon v12",status:"active",repo:"thefold-api"},{id:"T-005",title:"Legg til dark mode toggle",status:"pending",repo:"thefold-frontend"},{id:"T-004",title:"Oppdater README med nye endepunkter",status:"done",quality:7,repo:"thefold-api"}];
const count=alerts.length;
return(<div style={{position:"relative",zIndex:60}}><div onClick={()=>setOpen(p=>!p)} style={{cursor:"pointer",color:T.textMuted,display:"flex",alignItems:"center",padding:6,position:"relative"}}><BellIcon/>{count>0&&<div style={{position:"absolute",top:2,right:2,width:8,height:8,borderRadius:"50%",background:T.warning,border:`2px solid ${T.bg}`}}/>}</div>
{open&&<div style={{position:"absolute",top:"100%",right:0,marginTop:4,width:320,background:T.surface,border:`1px solid ${T.border}`,borderRadius:T.r,overflow:"hidden",boxShadow:"0 8px 24px rgba(0,0,0,0.5)",zIndex:100}}>
<div style={{padding:"12px 16px",borderBottom:`1px solid ${T.border}`,fontSize:11,fontWeight:600,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",fontFamily:T.mono}}>Krever oppmerksomhet ({count})</div>
{alerts.map((a,i)=>(<div key={i} onClick={()=>{onGoTask&&onGoTask(a.id);setOpen(false);}} style={{padding:"10px 16px",cursor:"pointer",borderBottom:i<alerts.length-1?`1px solid ${T.border}`:"none",display:"flex",alignItems:"center",gap:10}}><div style={{width:8,height:8,borderRadius:"50%",flexShrink:0,background:a.status==="active"?T.accent:a.status==="pending"?T.warning:a.quality&&a.quality<8?T.warning:T.success}}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,color:T.text,fontWeight:500,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{a.title}</div><div style={{fontSize:10,fontFamily:T.mono,color:T.textFaint,marginTop:1}}>{a.id} · {a.repo}</div></div><Tag variant={a.status==="active"?"accent":a.status==="pending"?"default":a.quality&&a.quality<8?"error":"success"}>{a.status==="active"?"pågår":a.status==="pending"?"venter":a.quality<8?"review":"ok"}</Tag></div>))}
</div>}
</div>);
}

function Tag({children,variant="default"}){
  const p={default:{bg:T.subtle,c:T.textSec,bc:T.border},accent:{bg:T.accentDim,c:T.accent,bc:"rgba(99,102,241,0.3)"},success:{bg:"rgba(52,211,153,0.1)",c:T.success,bc:"rgba(52,211,153,0.25)"},error:{bg:"rgba(239,68,68,0.1)",c:T.error,bc:"rgba(239,68,68,0.25)"},brand:{bg:"rgba(99,102,241,0.12)",c:T.brandLight,bc:"rgba(165,180,252,0.25)"},info:{bg:"rgba(99,102,241,0.1)",c:"#A5B4FC",bc:"rgba(99,102,241,0.25)"}}[variant]||{bg:T.subtle,c:T.textSec,bc:T.border};
  return(<span style={{display:"inline-flex",padding:"3px 10px",fontSize:11,fontWeight:500,fontFamily:T.mono,background:p.bg,color:p.c,border:`1px solid ${p.bc}`,borderRadius:10}}>{children}</span>);
}
function Btn({children,primary,sm,onClick,style:sx}){
  const[h,setH]=useState(false);
  return(<button onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,padding:sm?"5px 12px":"8px 18px",fontSize:sm?12:13,fontFamily:T.sans,fontWeight:primary?600:500,background:primary?(h?"#818CF8":T.accent):(h?T.subtle:"transparent"),color:primary?"#fff":T.text,border:`1px solid ${primary?"transparent":T.border}`,cursor:"pointer",transition:"all 0.15s",outline:"none",borderRadius:T.r,...sx}}>{children}</button>);
}
function Toggle({checked,onChange,label}){return(<label style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><div onClick={()=>onChange&&onChange(!checked)} style={{width:36,height:20,borderRadius:10,background:checked?T.accent:T.subtle,border:`1px solid ${checked?T.accent:T.border}`,position:"relative",transition:"all 0.2s",cursor:"pointer"}}><div style={{width:14,height:14,borderRadius:7,background:checked?"#fff":T.textMuted,position:"absolute",top:2,left:checked?19:2,transition:"left 0.2s"}}/></div>{label&&<span style={{fontSize:13,color:T.textSec,fontFamily:T.sans}}>{label}</span>}</label>);}
function PI({children,active,onClick,tooltip}){const[h,setH]=useState(false);return(<div onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} title={tooltip} style={{width:28,height:28,borderRadius:T.r,display:"flex",alignItems:"center",justifyContent:"center",background:active?T.accentDim:h?T.subtle:T.raised,border:`1px solid ${active?"rgba(99,102,241,0.4)":h?T.borderHover:T.border}`,cursor:"pointer",transition:"all 0.15s",flexShrink:0,color:active?T.accent:T.textMuted}}>{children}</div>);}
function MP({model="Sonnet 4.6"}){const[h,setH]=useState(false);return(<div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{display:"flex",alignItems:"center",gap:6,height:28,borderRadius:T.r,padding:"0 10px 0 0",background:h?T.subtle:T.raised,border:`1px solid ${h?T.borderHover:T.border}`,cursor:"pointer",transition:"all 0.15s"}}><div style={{width:28,height:28,borderRadius:T.r,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:11,fontWeight:600,color:T.textSec}}>A</span></div><span style={{fontSize:11,fontWeight:500,color:T.textSec,fontFamily:T.sans,whiteSpace:"nowrap"}}>{model}</span></div>);}
function SL({children}){return(<div style={{fontSize:10,fontWeight:600,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:12,fontFamily:T.mono}}>{children}</div>);}
function GR({children,mb}){return(<div style={{position:"relative",marginBottom:mb||0}}><div style={{position:"absolute",top:0,left:-SP,width:SP,height:1,background:T.border}}/><div style={{position:"absolute",top:0,right:-SP,width:SP,height:1,background:T.border}}/>{children}</div>);}
// Full-width grid row (uses CW instead of IW, no side padding lines needed)
function FGR({children,mb}){return(<div style={{position:"relative",marginBottom:mb||0}}>{children}</div>);}

function TP({active}){const ph=["Beskriv hva du jobber med...","Forklar et problem...","Hva trenger du hjelp med?"];const[pi,setPi]=useState(0);const[ci,setCi]=useState(0);const[d,setD]=useState(false);useEffect(()=>{if(active)return;let t;const p=ph[pi];if(!d){if(ci<p.length)t=setTimeout(()=>setCi(c=>c+1),40+Math.random()*40);else t=setTimeout(()=>setD(true),2000);}else{if(ci>0)t=setTimeout(()=>setCi(c=>c-1),20);else{setD(false);setPi(x=>(x+1)%ph.length);}}return()=>clearTimeout(t);},[ci,d,pi,active]);if(active)return null;return(<span style={{color:T.textFaint,pointerEvents:"none",userSelect:"none"}}>{ph[pi].slice(0,ci)}<span style={{animation:"blink 1s step-end infinite"}}>|</span></span>);}

function ChatInput({compact,repo,onSubmit,onRepoChange,ghost,onGhostChange}){
  const[v,setV]=useState("");const[st,setSt]=useState(false);const ty=v.length>0;
  const repos=["thefold-api","thefold-frontend"];const[rd,setRd]=useState(false);
  const doSend=()=>{if(v&&onSubmit){onSubmit(v,repo);setV("");}else if(v)setSt(true);};
  return(<div style={{width:"100%",maxWidth:compact?undefined:672,background:T.surface,borderRadius:T.r*1.5,position:"relative"}}>
    <div style={{height:compact?48:56,padding:"0 20px",display:"flex",alignItems:"center",position:"relative"}}>{!ty&&<div style={{position:"absolute",left:20,top:"50%",transform:"translateY(-50%)",fontSize:13,fontFamily:T.sans}}><TP active={ty}/></div>}<input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&v)doSend();}} style={{width:"100%",height:"100%",background:"transparent",border:"none",outline:"none",color:T.text,fontSize:13,fontFamily:T.sans,position:"relative",zIndex:1}}/></div>
    <div style={{height:compact?44:57,borderTop:`1px solid ${T.border}`,padding:"0 14px",display:"flex",alignItems:"center",justifyContent:"space-between"}}>
      <div style={{display:"flex",alignItems:"center",gap:6}}>
        <PI tooltip="Filer"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M7 3v8M3 7h8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg></PI>
        <PI tooltip="Privat — kun synlig for deg" active={ghost} onClick={()=>onGhostChange&&onGhostChange(!ghost)}><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M7 1C5 1 3.5 2.5 3 4c-.7 0-1.5.3-1.5 1.5C1.5 7 3 8 3 8s-.5 2 1 3.5c1 1 2 1.5 3 1.5s2-.5 3-1.5c1.5-1.5 1-3.5 1-3.5s1.5-1 1.5-2.5C12.5 4.3 11.7 4 11 4c-.5-1.5-2-3-4-3z" stroke="currentColor" strokeWidth="1.1" fill="none"/><circle cx="5.5" cy="6" r="1" fill="currentColor"/><circle cx="8.5" cy="6" r="1" fill="currentColor"/></svg></PI>
        {!ghost&&<><PI tooltip="Sub-agenter"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="4" r="2.5" stroke="currentColor" strokeWidth="1.1"/><circle cx="3.5" cy="6" r="1.5" stroke="currentColor" strokeWidth="1"/><circle cx="10.5" cy="6" r="1.5" stroke="currentColor" strokeWidth="1"/><path d="M1 12c0-2 1.5-3 2.5-3M13 12c0-2-1.5-3-2.5-3M3.5 12c0-2.5 1.5-4 3.5-4s3.5 1.5 3.5 4" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round"/></svg></PI>
        <PI tooltip="Skills"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M8 2L4 8h3l-1 4 4-6H7l1-4z" stroke="currentColor" strokeWidth="1.1" strokeLinejoin="round"/></svg></PI>
        <div style={{marginLeft:4,position:"relative",zIndex:50}}><div onClick={()=>setRd(p=>!p)} style={{display:"flex",alignItems:"center",gap:5,padding:"3px 10px",background:T.subtle,border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.mono,color:repo?T.textSec:T.textFaint,cursor:"pointer"}}><svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.2"><path d="M2 3.5C2 2.67 2.67 2 3.5 2h2l1 1.5h2c.83 0 1.5.67 1.5 1.5v4c0 .83-.67 1.5-1.5 1.5h-5A1.5 1.5 0 012 9V3.5z"/></svg>{repo||"Velg repo"}<svg width="10" height="10" viewBox="0 0 10 10" fill="none"><path d="M2.5 4L5 6.5 7.5 4" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"/></svg></div>{rd&&<div style={{position:"absolute",bottom:"100%",left:0,marginBottom:4,background:T.surface,border:`1px solid ${T.border}`,borderRadius:T.r,overflow:"hidden",zIndex:100,minWidth:180,boxShadow:"0 4px 16px rgba(0,0,0,0.5)"}}>{repos.map(r=>(<div key={r} onClick={()=>{onRepoChange&&onRepoChange(r);setRd(false);}} style={{padding:"8px 12px",fontSize:11,fontFamily:T.mono,color:r===repo?T.text:T.textSec,background:r===repo?T.subtle:"transparent",cursor:"pointer",borderBottom:`1px solid ${T.border}`}}>{r}</div>))}<div onClick={()=>{onRepoChange&&onRepoChange(null);setRd(false);}} style={{padding:"8px 12px",fontSize:11,fontFamily:T.mono,color:T.textFaint,cursor:"pointer"}}>Ingen repo</div></div>}</div></>}
      </div>
      <div style={{display:"flex",alignItems:"center",gap:6}}><MP/><PI active={ty||st} onClick={doSend} tooltip={st?"Stopp":"Send"}>{st?<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><rect x="2" y="2" width="8" height="8" rx="0" fill="currentColor"/></svg>:<svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M7 11V3M7 3L3.5 6.5M7 3l3.5 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>}</PI></div>
    </div>
  </div>);
}

function ChatComposer({onSubmit,heading}){
  const[repo,setRepo]=useState("thefold-api");const[ghost,setGhost]=useState(false);
  return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",flex:1,minHeight:400}}>
    <div style={{paddingBottom:32,textAlign:"center"}}><h2 style={{fontSize:32,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont}}>{heading||"Når AI sier umulig, sier Mikael Kråkenes neste"}</h2></div>
    <div style={{width:"100%",maxWidth:672,position:"relative"}}>
      <div style={{position:"absolute",bottom:-12,left:"50%",transform:"translateX(-50%)",width:"80%",height:40,background:"radial-gradient(ellipse at center, rgba(99,102,241,0.15) 0%, transparent 70%)",pointerEvents:"none",filter:"blur(20px)",zIndex:0}}/>
      <div style={{position:"relative",zIndex:1}}><ChatInput repo={repo} onSubmit={(msg,r)=>onSubmit&&onSubmit(msg,r,ghost)} onRepoChange={setRepo} ghost={ghost} onGhostChange={setGhost}/></div>
    </div>
  </div>);
}

function AgentStream(){const[ex,setEx]=useState({0:true,1:false,2:false});const tg=(i)=>setEx(p=>({...p,[i]:!p[i]}));const ts=[{t:"Lager ny nettside",s:"active",st:[{x:"Henter komponenter",d:true},{x:"Bygger layout",d:true},{x:"Skriver kode",d:false,a:true},{x:"Integrerer API",d:false}]},{t:"Oppdaterer auth",s:"done",st:[{x:"Analyserer auth.ts",d:true},{x:"Refresh-token",d:true},{x:"Tester rotering",d:true}]},{t:"Kjører tester",s:"pending",st:[{x:"Unit tests",d:false},{x:"Integration tests",d:false}]}];
return(<div style={{display:"flex",flexDirection:"column",gap:2,maxWidth:500}}>{ts.map((task,ti)=>(<div key={ti}><div onClick={()=>tg(ti)} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 0",cursor:"pointer"}}><div style={{width:16,height:16,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{task.s==="pending"?<div style={{width:4,height:4,borderRadius:"50%",background:T.textFaint}}/>:<CI color={task.s==="done"?T.textMuted:T.textFaint} size={14}/>}</div><span style={{fontSize:13,fontWeight:500,fontFamily:T.sans,position:"relative",overflow:"hidden",color:task.s==="done"?T.textSec:task.s==="active"?T.text:T.textFaint}}>{task.t}{task.s==="active"&&<span style={{position:"absolute",top:0,left:0,right:0,bottom:0,background:"linear-gradient(90deg,transparent 0%,rgba(99,102,241,0.18) 50%,transparent 100%)",backgroundSize:"200% 100%",animation:"shimmerMove 2s linear infinite"}}/>}</span><svg width="12" height="12" viewBox="0 0 12 12" fill="none" style={{marginLeft:"auto",flexShrink:0,transition:"transform 0.2s",transform:ex[ti]?"rotate(0)":"rotate(-90deg)"}}><path d="M3 4.5L6 7.5L9 4.5" stroke={T.textFaint} strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg></div>{ex[ti]&&<div style={{paddingLeft:24,paddingBottom:6,display:"flex",flexDirection:"column",gap:3}}>{task.st.map((s,si)=>(<div key={si} style={{display:"flex",alignItems:"center",gap:8,padding:"3px 0"}}>{s.d?<CI color={T.textMuted} size={12}/>:s.a?<div style={{width:12,height:12,borderRadius:"50%",border:`2px solid ${T.accent}`,borderTopColor:"transparent",animation:"spin 0.7s linear infinite"}}/>:<div style={{width:12,height:12,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:4,height:4,borderRadius:"50%",background:T.textFaint}}/></div>}<span style={{fontSize:12,fontFamily:T.sans,color:s.d?T.textMuted:s.a?T.textSec:T.textFaint}}>{s.x}</span></div>))}</div>}</div>))}</div>);}

// ═══ OVERVIEW ═══
function OverviewPage({onStartChat}){return(<><ChatComposer heading="Når AI sier umulig, sier Mikael Kråkenes neste" onSubmit={(msg,repo,ghost)=>onStartChat&&onStartChat(msg,repo,ghost)}/>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"TOKENS I DAG",v:"12.4k",t:"+8.3%",c:T.success},{l:"KOSTNAD",v:"$1.24",t:"-2.1%",c:T.error},{l:"AKTIVE TASKS",v:"3"},{l:"SUCCESS RATE",v:"94%",t:"+1.2%",c:T.success}].map((s,i)=>(<div key={i} style={{padding:"18px 24px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",lineHeight:1}}>{s.v}</div>{s.t&&<div style={{marginTop:6,fontSize:11,fontFamily:T.mono,color:s.c}}>{s.t}</div>}</div>))}</div></GR>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:20,borderRight:`1px solid ${T.border}`}}><SL>SISTE AKTIVITET</SL>{["Auth-middleware oppdatert","PR #42 godkjent","Tester bestått (12/12)","README oppdatert"].map((it,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"7px 0",borderBottom:i<3?`1px solid ${T.border}`:"none"}}><div style={{width:6,height:6,borderRadius:"50%",background:[T.success,T.accent,T.success,T.brandLight][i]}}/><span style={{fontSize:12,color:T.textSec,flex:1}}>{it}</span><span style={{fontSize:10,color:T.textFaint,fontFamily:T.mono}}>{["2m","14m","1h","2h"][i]}</span></div>))}</div><div style={{padding:20}}><SL>KONTROLLER</SL><div style={{display:"flex",flexDirection:"column",gap:10}}><Toggle checked={true} onChange={()=>{}} label="Agent-modus"/><Toggle checked={false} onChange={()=>{}} label="Sub-agenter"/><Toggle checked={false} onChange={()=>{}} label="Privat"/></div></div></div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:20,borderRight:`1px solid ${T.border}`}}><SL>KOMPONENTER</SL><div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:12}}><Btn primary sm>Primary</Btn><Btn sm>Secondary</Btn></div><div style={{display:"flex",flexWrap:"wrap",gap:6}}><Tag>default</Tag><Tag variant="accent">aktiv</Tag><Tag variant="success">ok</Tag><Tag variant="error">feil</Tag></div></div><div style={{padding:20}}><SL>TYPOGRAFI</SL><div style={{fontSize:24,fontWeight:600,color:T.text,letterSpacing:"-0.025em",lineHeight:1.2,marginBottom:8,fontFamily:T.brandFont}}>Display</div><div style={{fontSize:14,color:T.textSec,lineHeight:1.5,marginBottom:4}}>Body text i Suisse Intl 400.</div><div style={{fontSize:11,fontFamily:T.mono,color:T.textFaint}}>mono: Geist Mono</div></div></div></GR></>);}

// ═══ CHAT — uses full CW width ═══
function ChatPage({initialMsg,initialRepo,initialGhost}){const[ac,setAc]=useState(initialMsg?0:null);const[newChat,setNewChat]=useState(!initialMsg);const[tab,setTab]=useState(initialGhost?"Privat":"Repo");const convs=[{id:0,t:initialMsg||"Auth-middleware refactor",r:initialGhost?null:(initialRepo||"thefold-api"),time:"nå",ur:true,priv:!!initialGhost},{id:1,t:"Frontend deployment fix",r:"thefold-frontend",time:"14m",ur:false},{id:2,t:"Database migration",r:"thefold-api",time:"1t",ur:false},{id:3,t:"Personlig notat",r:null,time:"3t",ur:false,priv:true},{id:4,t:"Component library audit",r:"thefold-frontend",time:"1d",ur:false},{id:5,t:"Hemmeleg plan",r:null,time:"2d",ur:false,priv:true}];
const filtered=convs.filter(c=>tab==="Privat"?c.priv:!c.priv);
const msgs=initialMsg?[{role:"user",content:initialMsg},{role:"assistant",agent:true}]:[{role:"user",content:"Kan du oppdatere auth-middleware med refresh-token støtte?"},{role:"assistant",agent:true},{role:"assistant",content:"Ferdig! gateway/auth.ts oppdatert med refresh-token. Roteres automatisk, utløpstid 30 dager. Kjøre tester?"},{role:"user",content:"Ja, kjør testene."},{role:"assistant",content:"Alle 12 tester bestått. Auth-middleware klar for review. Opprette PR?"}];
const startNewChat=(msg,repo,ghost)=>{setNewChat(false);setAc(0);if(ghost)setTab("Privat");};
const cur=ac!==null?convs.find(c=>c.id===ac):null;
return(<div style={{border:`1px solid ${T.border}`,borderRadius:T.r,display:"grid",gridTemplateColumns:"280px 1fr",minHeight:"calc(100vh - 130px)",position:"relative",overflow:"hidden"}}><PC/>
<div style={{borderRight:`1px solid ${T.border}`,display:"flex",flexDirection:"column"}}><div style={{padding:"16px 16px 12px",borderBottom:`1px solid ${T.border}`}}><Btn primary sm style={{width:"100%"}} onClick={()=>{setNewChat(true);setAc(null);}}>+ Ny samtale</Btn></div><div style={{padding:"8px",display:"flex",gap:4,borderBottom:`1px solid ${T.border}`}}>{["Repo","Privat"].map((f,i)=>(<div key={i} onClick={()=>setTab(f)} style={{fontSize:11,fontFamily:T.mono,padding:"4px 8px",background:tab===f?T.subtle:"transparent",color:tab===f?T.text:T.textMuted,cursor:"pointer",border:`1px solid ${tab===f?T.border:"transparent"}`,borderRadius:6}}>{f}</div>))}</div>
<div style={{flex:1,overflow:"auto"}}>{filtered.map(c=>(<div key={c.id} onClick={()=>{setAc(c.id);setNewChat(false);}} style={{padding:"12px 16px",cursor:"pointer",background:ac===c.id&&!newChat?T.subtle:"transparent",borderBottom:`1px solid ${T.border}`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}>{c.priv&&<svg width="12" height="12" viewBox="0 0 14 14" fill="none"><path d="M7 1C5 1 3.5 2.5 3 4c-.7 0-1.5.3-1.5 1.5C1.5 7 3 8 3 8s-.5 2 1 3.5c1 1 2 1.5 3 1.5s2-.5 3-1.5c1.5-1.5 1-3.5 1-3.5s1.5-1 1.5-2.5C12.5 4.3 11.7 4 11 4c-.5-1.5-2-3-4-3z" stroke={T.textFaint} strokeWidth="1.1" fill="none"/></svg>}<span style={{fontSize:13,fontWeight:c.ur?600:400,color:c.ur?T.text:T.textSec,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{c.t}</span></div><div style={{display:"flex",alignItems:"center",gap:8}}>{c.r&&<span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{c.r}</span>}<span style={{fontSize:10,color:T.textFaint,marginLeft:"auto"}}>{c.time}</span></div></div>))}</div></div>
{newChat?<div style={{display:"flex",flexDirection:"column"}}><ChatComposer onSubmit={startNewChat}/></div>:<div style={{display:"flex",flexDirection:"column"}}><div style={{padding:"14px 20px",borderBottom:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontSize:14,fontWeight:600,color:T.text}}>{cur?cur.t:"—"}</div>{cur&&cur.r&&<div style={{fontSize:11,fontFamily:T.mono,color:T.textFaint,marginTop:2}}>{cur.r}</div>}</div><div style={{display:"flex",gap:6}}><Tag variant="brand">sonnet-4-6</Tag></div></div>
<div style={{flex:1,overflow:"auto",padding:"20px 24px",display:"flex",flexDirection:"column",gap:20}}>{msgs.map((m,i)=>(<div key={i} style={{display:"flex",gap:10,alignItems:"flex-start",justifyContent:m.role==="user"?"flex-end":"flex-start"}}>{m.role==="assistant"&&<div style={{width:28,height:28,borderRadius:T.r,flexShrink:0,background:T.surface,border:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"center"}}><RI size={16}/></div>}<div style={{maxWidth:540}}>{m.agent?<AgentStream/>:m.role==="user"?<div style={{background:T.subtle,border:`1px solid ${T.border}`,borderRadius:T.r,padding:"10px 16px",fontSize:13,lineHeight:1.6,color:T.text,fontFamily:T.sans}}>{m.content}</div>:<div style={{fontSize:13,lineHeight:1.65,color:T.text,fontFamily:T.sans,paddingTop:4}}>{m.content}</div>}</div></div>))}</div>
<div style={{padding:"12px 20px",borderTop:`1px solid ${T.border}`}}><ChatInput compact repo={cur&&cur.r||undefined} ghost={cur&&cur.priv}/></div></div>}</div>);}

// ═══ TASKS ═══
function TasksPage(){const[sel,setSel]=useState(null);const tasks=[
{id:"T-001",title:"Implementer refresh-token i auth",status:"done",repo:"thefold-api",time:"2t",quality:8,files:["gateway/auth.ts","gateway/auth.test.ts"],concerns:["Mangler rate limiting på login"],cost:"$0.42",tokens:"8.2k",duration:"4m 12s",source:"linear",linearId:"TF-142"},
{id:"T-002",title:"Fiks deployment pipeline",status:"done",repo:"thefold-frontend",time:"5t",quality:9,files:["deploy.yml","Dockerfile"],concerns:[],cost:"$0.18",tokens:"3.1k",duration:"1m 45s",source:"linear",linearId:"TF-138"},
{id:"T-003",title:"Database migrasjon v12",status:"active",repo:"thefold-api",time:"12m",quality:null,files:["migrations/012.sql"],concerns:[],cost:"$0.08",tokens:"1.4k",duration:null,source:"linear",linearId:"TF-155"},
{id:"T-004",title:"Oppdater README med nye endepunkter",status:"done",repo:"thefold-api",time:"1d",quality:7,files:["README.md","docs/api.md","docs/auth.md"],concerns:["Mangler eksempler for error-responses","Noen endepunkter udokumentert"],cost:"$0.06",tokens:"1.1k",duration:"52s",source:"manual",linearId:null},
{id:"T-005",title:"Legg til dark mode toggle",status:"pending",repo:"thefold-frontend",time:"2d",quality:null,files:[],concerns:[],cost:"$0.00",tokens:"0",duration:null,source:"linear",linearId:"TF-160"},
];
const t=sel!==null?tasks.find(x=>x.id===sel):null;
return(<><div style={{paddingTop:40,paddingBottom:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Tasks</h2><p style={{fontSize:13,color:T.textMuted}}>Oppgaver utført av agenten med kvalitetsrapport.</p></div><div style={{display:"flex",gap:8}}><Btn sm><svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{marginRight:4}}><path d="M7 1v12M1 7h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg>Ny task</Btn><Btn primary sm><svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{marginRight:4}}><rect x="2" y="2" width="10" height="10" rx="1" stroke="currentColor" strokeWidth="1.2" fill="none"/><path d="M5 5l4 2-4 2V5z" fill="currentColor"/></svg>Importer fra Linear</Btn></div></div></div>
<GR><div style={{display:"grid",gridTemplateColumns:t?"1fr 1fr":"1fr",border:`1px solid ${T.border}`,minHeight:400,position:"relative",overflow:"hidden"}}><PC/>
<div style={{borderRight:t?`1px solid ${T.border}`:"none"}}>{tasks.map((tk,i)=>(<div key={tk.id} onClick={()=>setSel(tk.id===sel?null:tk.id)} style={{padding:"14px 20px",cursor:"pointer",background:sel===tk.id?T.subtle:"transparent",borderBottom:i<tasks.length-1?`1px solid ${T.border}`:"none",borderLeft:sel===tk.id?`3px solid ${T.accent}`:"3px solid transparent",transition:"all 0.1s"}}>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{tk.id}</span><span style={{fontSize:13,fontWeight:500,color:T.text,flex:1}}>{tk.title}</span><Tag variant={tk.status==="done"?"success":tk.status==="active"?"accent":"default"}>{tk.status}</Tag></div>
<div style={{display:"flex",gap:12}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{tk.repo}</span>{tk.source==="linear"&&<span style={{fontSize:10,fontFamily:T.mono,color:"#A5B4FC"}}>{tk.linearId}</span>}{tk.quality&&<span style={{fontSize:10,fontFamily:T.mono,color:tk.quality>=8?T.success:tk.quality>=6?T.warning:T.error}}>kvalitet: {tk.quality}/10</span>}<span style={{fontSize:10,color:T.textFaint,marginLeft:"auto"}}>{tk.time}</span></div></div>))}</div>
{t&&<div style={{padding:24,overflow:"auto"}}><div style={{marginBottom:20}}><div style={{fontSize:18,fontWeight:600,color:T.text,fontFamily:T.brandFont,marginBottom:4}}>{t.title}</div><div style={{display:"flex",gap:8,marginBottom:16}}><Tag variant={t.status==="done"?"success":"accent"}>{t.status}</Tag><Tag>{t.repo}</Tag>{t.source==="linear"&&<Tag variant="info">{t.linearId}</Tag>}{t.source==="manual"&&<Tag>manuell</Tag>}</div></div>
{t.quality!==null&&<><SL>KVALITETSRAPPORT</SL><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:1,marginBottom:20}}>{[{l:"KVALITET",v:`${t.quality}/10`,c:t.quality>=8?T.success:t.quality>=6?T.warning:T.error},{l:"KOSTNAD",v:t.cost},{l:"VARIGHET",v:t.duration||"—"}].map((m,i)=>(<div key={i} style={{background:T.subtle,padding:"12px 16px",borderRadius:6}}><div style={{fontSize:10,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>{m.l}</div><div style={{fontSize:20,fontWeight:600,color:m.c||T.text}}>{m.v}</div></div>))}</div>
<div style={{marginBottom:20}}><div style={{height:8,background:T.subtle,borderRadius:4,overflow:"hidden",marginBottom:4}}><div style={{width:`${t.quality*10}%`,height:"100%",background:t.quality>=8?T.success:t.quality>=6?T.warning:T.error}}/></div><div style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>Score: {t.quality*10}%</div></div></>}
<SL>FILER ENDRET</SL><div style={{marginBottom:20}}>{t.files.map((f,i)=>(<div key={i} style={{padding:"6px 0",borderBottom:i<t.files.length-1?`1px solid ${T.border}`:"none",fontSize:12,fontFamily:T.mono,color:T.textSec}}>{f}</div>))}{t.files.length===0&&<div style={{fontSize:12,color:T.textFaint}}>Ingen filer ennå</div>}</div>
{t.concerns.length>0&&<><SL>BEKYMRINGER</SL>{t.concerns.map((c,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 0",borderBottom:i<t.concerns.length-1?`1px solid ${T.border}`:"none"}}><div style={{width:6,height:6,borderRadius:"50%",background:T.warning}}/><span style={{fontSize:12,color:T.textSec}}>{c}</span></div>))}</>}
<div style={{marginTop:20,display:"flex",gap:8}}><Btn primary sm>Godkjenn</Btn><Btn sm>Be om endringer</Btn><Btn sm style={{color:T.error,borderColor:"rgba(99,102,241,0.3)"}}>Avvis</Btn></div></div>}
</div></GR><GR mb={40}><div style={{height:1}}/></GR></>);}

// ═══ KOMPONENTER ═══
function KomponenterPage(){const cs=[{n:"AuthMiddleware",d:"JWT-validering med refresh-token",t:["backend","auth"],s:"stable",i:142},{n:"ChatBubble",d:"Meldings-komponent med markdown",t:["frontend","chat"],s:"stable",i:89},{n:"AgentProgress",d:"Collapsible steg-liste for agent",t:["frontend","agent"],s:"beta",i:34},{n:"RateLimiter",d:"Token-bucket rate limiter med Redis",t:["backend","infra"],s:"stable",i:201},{n:"FileUploader",d:"Drag-drop opplasting med progress",t:["frontend","ui"],s:"stable",i:167},{n:"WebhookHandler",d:"Webhook-mottak med HMAC",t:["backend","api"],s:"stable",i:78},{n:"PixelCorners",d:"Dekorativ pixel-corner",t:["frontend","design"],s:"beta",i:23},{n:"HealthMonitor",d:"Repo helse-sjekk med alerting",t:["backend","devops"],s:"alpha",i:12}];
const[fi,setFi]=useState("all");const[se,setSe]=useState("");const fl=cs.filter(c=>{if(se&&!c.n.toLowerCase().includes(se.toLowerCase())&&!c.d.toLowerCase().includes(se.toLowerCase()))return false;if(fi==="all")return true;return c.t.includes(fi);});
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Komponenter</h2><p style={{fontSize:13,color:T.textMuted}}>Gjenbrukbare komponenter fra registry.</p></div>
<GR><div style={{border:`1px solid ${T.border}`,padding:"14px 20px",display:"flex",alignItems:"center",gap:12,position:"relative",overflow:"hidden"}}><PC/><svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke={T.textMuted} strokeWidth="1.3"><circle cx="7" cy="7" r="5"/><path d="M11 11l3.5 3.5"/></svg><input value={se} onChange={e=>setSe(e.target.value)} placeholder="Søk..." style={{flex:1,background:"transparent",border:"none",outline:"none",color:T.text,fontSize:13,fontFamily:T.sans}}/><div style={{display:"flex",gap:4}}>{["all","frontend","backend"].map(f=>(<div key={f} onClick={()=>setFi(f)} style={{fontSize:11,fontFamily:T.mono,padding:"4px 10px",background:fi===f?T.subtle:"transparent",color:fi===f?T.text:T.textMuted,cursor:"pointer",border:`1px solid ${fi===f?T.border:"transparent"}`,borderRadius:6}}>{f}</div>))}</div></div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/>{fl.map((c,i)=>{const ir=i%2===1;const nl=i<fl.length-2||(fl.length%2===1&&i<fl.length-1);return(<div key={i} style={{padding:24,borderRight:ir?"none":`1px solid ${T.border}`,borderBottom:nl?`1px solid ${T.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><span style={{fontSize:15,fontWeight:600,color:T.text,fontFamily:T.brandFont}}>{c.n}</span><Tag variant={c.s==="stable"?"success":c.s==="beta"?"accent":"default"}>{c.s}</Tag></div><p style={{fontSize:12,color:T.textMuted,lineHeight:1.5,marginBottom:12}}>{c.d}</p><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",gap:4}}>{c.t.map(t=>(<Tag key={t}>{t}</Tag>))}</div><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{c.i}</span><Btn sm primary>Bruk</Btn></div></div></div>);})}</div></GR></>);}

// ═══ AI ═══
function AIPage(){const ps=[{n:"Anthropic",s:"active",b:"$42.18",u:"68%"},{n:"OpenRouter",s:"active",b:"$18.50",u:"22%"},{n:"Fireworks",s:"inactive",b:"$5.00",u:"8%"},{n:"OpenAI",s:"inactive",b:"$0.00",u:"2%"}];const ms=[{n:"claude-sonnet-4",p:"Anthropic",c:"$3/$15",r:1842,s:"98.2%",pr:true},{n:"claude-haiku-4.5",p:"Anthropic",c:"$0.80/$4",r:3201,s:"97.8%"},{n:"deepseek-r1",p:"OpenRouter",c:"$0.55/$2.19",r:445,s:"94.1%"},{n:"llama-4-scout",p:"OpenRouter",c:"$0.15/$0.60",r:122,s:"91.3%"}];const ch=[{d:"Man",c:1.24},{d:"Tir",c:2.18},{d:"Ons",c:0.89},{d:"Tor",c:3.42},{d:"Fre",c:1.67},{d:"Lør",c:0.34},{d:"Søn",c:0.12}];const mx=Math.max(...ch.map(c=>c.c));
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>AI</h2><p style={{fontSize:13,color:T.textMuted}}>Providers, modeller, kostnader og saldo.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{ps.map((p,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><span style={{fontSize:14,fontWeight:600,color:T.text,fontFamily:T.brandFont}}>{p.n}</span><Tag variant={p.s==="active"?"accent":"default"}>{p.s}</Tag></div><div style={{fontSize:10,color:T.textMuted,textTransform:"uppercase",marginBottom:4}}>SALDO</div><div style={{fontSize:22,fontWeight:600,color:T.text,marginBottom:8}}>{p.b}</div><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{flex:1,height:4,background:T.subtle,overflow:"hidden"}}><div style={{width:p.u,height:"100%",background:T.accent}}/></div><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{p.u}</span></div></div>))}</div></GR>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:20,borderRight:`1px solid ${T.border}`}}><SL>KOSTNAD 7 DAGER</SL><div style={{display:"flex",alignItems:"flex-end",gap:8,height:120,paddingTop:8}}>{ch.map((c,i)=>(<div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:6}}><span style={{fontSize:9,fontFamily:T.mono,color:T.textFaint}}>${c.c}</span><div style={{width:"100%",background:T.accent,height:`${(c.c/mx)*80}px`,opacity:0.8+((c.c/mx)*0.2)}}/><span style={{fontSize:9,fontFamily:T.mono,color:T.textFaint}}>{c.d}</span></div>))}</div><div style={{marginTop:16,display:"flex",justifyContent:"space-between",borderTop:`1px solid ${T.border}`,paddingTop:12}}><div><div style={{fontSize:10,color:T.textMuted}}>TOTALT</div><div style={{fontSize:18,fontWeight:600,color:T.text}}>$9.86</div></div><div><div style={{fontSize:10,color:T.textMuted}}>SNITT/DAG</div><div style={{fontSize:18,fontWeight:600,color:T.text}}>$1.41</div></div><div><div style={{fontSize:10,color:T.textMuted}}>TREND</div><div style={{fontSize:18,fontWeight:600,color:T.success}}>-12%</div></div></div></div>
<div style={{padding:20}}><SL>TOKEN-BUDSJETT PER FASE</SL>{[{p:"Planlegging",b:"4k",u:2800,m:4000},{p:"Koding",b:"16k",u:12400,m:16000},{p:"Validering",b:"8k",u:3200,m:8000},{p:"Review",b:"4k",u:1600,m:4000}].map((p,i)=>(<div key={i} style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:12,color:T.textSec}}>{p.p}</span><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{p.u.toLocaleString()}/{p.b}</span></div><div style={{height:6,background:T.subtle,borderRadius:3,overflow:"hidden"}}><div style={{width:`${(p.u/p.m)*100}%`,height:"100%",background:p.u/p.m>0.8?T.error:T.accent}}/></div></div>))}</div></div></GR>
<GR mb={40}><div style={{border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:"14px 20px",borderBottom:`1px solid ${T.border}`}}><SL>MODELLER</SL></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1.2fr 1fr 1fr 80px",padding:"10px 20px",borderBottom:`1px solid ${T.border}`,background:T.subtle}}>{["MODELL","PROVIDER","PRIS","REQUESTS","SUCCESS",""].map((h,i)=>(<div key={i} style={{fontSize:10,fontWeight:600,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",fontFamily:T.mono}}>{h}</div>))}</div>{ms.map((m,i)=>(<div key={i} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1.2fr 1fr 1fr 80px",padding:"12px 20px",borderBottom:i<ms.length-1?`1px solid ${T.border}`:"none",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:13,fontWeight:500,color:T.text,fontFamily:T.mono}}>{m.n}</span>{m.pr&&<Tag variant="accent">primær</Tag>}</div><span style={{fontSize:12,color:T.textSec}}>{m.p}</span><span style={{fontSize:12,fontFamily:T.mono,color:T.textMuted}}>{m.c}</span><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{m.r.toLocaleString()}</span><span style={{fontSize:12,fontFamily:T.mono,color:parseFloat(m.s)>96?T.success:T.warning}}>{m.s}</span><Btn sm>Endre</Btn></div>))}</div></GR></>);}

// ═══ INTEGRASJONER ═══
function IntegrasjonerPage(){const ints=[{n:"Slack",cat:"Kommunikasjon",s:"connected",desc:"Webhook-varsler til Slack-kanaler",url:"hooks.slack.com/...xYz",ev:["task.completed","review.pending","health.alert"]},{n:"Discord",cat:"Kommunikasjon",s:"connected",desc:"Varsler til Discord-server",url:"discord.com/api/webhooks/...",ev:["task.completed","review.pending"]},{n:"Linear",cat:"Prosjektstyring",s:"connected",desc:"Synkroniserer oppgaver med Linear",ev:["task.created","task.updated","task.completed"]},{n:"GitHub",cat:"Kode",s:"connected",desc:"Repo-tilgang, PR-oppretting, webhooks",ev:["push","pull_request","review"]},{n:"Sentry",cat:"Observability",s:"disconnected",desc:"Feilsporing og ytelsesovervåking"},{n:"Vercel",cat:"Deploy",s:"disconnected",desc:"Automatisk deployment ved PR-merge"},{n:"Resend",cat:"E-post",s:"connected",desc:"OTP og transaksjonell e-post",ev:["auth.otp"]},{n:"Brave Search",cat:"MCP",s:"connected",desc:"Web-søk for agent via MCP",ev:["agent.search"]}];
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Integrasjoner</h2><p style={{fontSize:13,color:T.textMuted}}>Eksterne tjenester og tilkoblinger.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"TILKOBLET",v:ints.filter(i=>i.s==="connected").length},{l:"FRAKOBLET",v:ints.filter(i=>i.s==="disconnected").length},{l:"EVENTS I DAG",v:"48"},{l:"FEIL",v:"0"}].map((s,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",lineHeight:1}}>{s.v}</div></div>))}</div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/>{ints.map((ig,i)=>{const ir=i%2===1;const nl=i<ints.length-2||(ints.length%2===1&&i<ints.length-1);return(<div key={i} style={{padding:20,borderRight:ir?"none":`1px solid ${T.border}`,borderBottom:nl?`1px solid ${T.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><span style={{fontSize:15,fontWeight:600,color:T.text,fontFamily:T.brandFont}}>{ig.n}</span><Tag variant={ig.s==="connected"?"success":"default"}>{ig.s==="connected"?"tilkoblet":"frakoblet"}</Tag></div><div style={{fontSize:10,fontFamily:T.mono,color:T.textFaint,marginBottom:6}}>{ig.cat}</div><p style={{fontSize:12,color:T.textMuted,lineHeight:1.5,marginBottom:10}}>{ig.desc}</p>{ig.ev&&<div style={{display:"flex",flexWrap:"wrap",gap:4}}>{ig.ev.map(e=>(<Tag key={e}>{e}</Tag>))}</div>}{!ig.ev&&<Btn sm primary>Koble til</Btn>}</div>);})}</div></GR></>);}

// ═══ MCP ═══
function MCPPage(){const svs=[{n:"context7",cat:"docs",s:"installed",desc:"Oppdatert bibliotekdokumentasjon via Context7",tools:["resolve-library-id","get-library-docs"],health:"healthy"},{n:"brave-search",cat:"general",s:"available",desc:"Web-søk for agenten via Brave Search API",tools:["web_search","local_search"],health:"unknown"},{n:"filesystem",cat:"code",s:"available",desc:"Les/skriv filer i sandkassen",tools:["read_file","write_file","list_directory"],health:"unknown"},{n:"github",cat:"code",s:"available",desc:"GitHub API-tilgang for repo-operasjoner",tools:["create_issue","create_pull_request","search_code"],health:"unknown"},{n:"linear-mcp",cat:"general",s:"installed",desc:"Synkroniser oppgaver med Linear",tools:["list_issues","create_issue","update_issue"],health:"healthy"},{n:"sentry",cat:"general",s:"available",desc:"Feilsporing og ytelsesovervåking",tools:["search_issues","get_event"],health:"unknown"},{n:"puppeteer",cat:"general",s:"available",desc:"Nettleser-automasjon for testing og scraping",tools:["navigate","screenshot","click"],health:"unknown"}];
const[rte,setRte]=useState(true);
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>MCP Servere</h2><p style={{fontSize:13,color:T.textMuted}}>Model Context Protocol — verktøy agenten kan bruke.</p></div>
<GR><div style={{border:`1px solid ${T.border}`,padding:"14px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",position:"relative",overflow:"hidden"}}><PC/><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:12,color:T.textSec}}>MCP Routing</span><Toggle checked={rte} onChange={setRte} label={rte?"Aktivert":"Deaktivert"}/></div><div style={{display:"flex",gap:8}}><Tag variant={rte?"success":"default"}>{rte?"routing aktiv":"routing av"}</Tag><Tag>{svs.filter(s=>s.s==="installed").length} installert</Tag><Tag>{svs.length} totalt</Tag></div></div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/>{svs.map((s,i)=>{const ir=i%2===1;const nl=i<svs.length-2||(svs.length%2===1&&i<svs.length-1);return(<div key={i} style={{padding:20,borderRight:ir?"none":`1px solid ${T.border}`,borderBottom:nl?`1px solid ${T.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{fontSize:15,fontWeight:600,color:T.text,fontFamily:T.brandFont}}>{s.n}</span><Tag variant={s.s==="installed"?"success":"default"}>{s.s}</Tag>{s.health==="healthy"&&<Tag variant="success">healthy</Tag>}</div><div style={{fontSize:10,fontFamily:T.mono,color:T.textFaint,marginBottom:6}}>{s.cat}</div><p style={{fontSize:12,color:T.textMuted,lineHeight:1.5,marginBottom:10}}>{s.desc}</p><div style={{marginBottom:10}}><div style={{fontSize:10,color:T.textFaint,marginBottom:4}}>TOOLS</div><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{s.tools.map(t=>(<Tag key={t}>{t}</Tag>))}</div></div><div style={{display:"flex",gap:6}}>{s.s==="installed"?<><Btn sm>Konfigurer</Btn><Btn sm style={{color:T.error,borderColor:"rgba(99,102,241,0.3)"}}>Avinstaller</Btn></>:<Btn sm primary>Installer</Btn>}</div></div>);})}</div></GR></>);}

// ═══ MEMORY ═══
function MemoryPage(){const mems=[{id:"M-001",content:"JWT refresh-token mønster brukt i gateway/auth.ts",type:"code_pattern",repo:"thefold-api",trust:"agent",relevance:0.92,accessed:14,age:"2d"},{id:"M-002",content:"Bruker Encore.ts api() for alle endepunkter med auth: true",type:"decision",repo:null,trust:"system",relevance:0.98,accessed:47,age:"14d"},{id:"M-003",content:"Docker sandbox med --network=none for sikkerhet",type:"decision",repo:null,trust:"system",relevance:0.85,accessed:8,age:"7d"},{id:"M-004",content:"Rate limiter bug: token-bucket reset ved midnatt UTC",type:"error_pattern",repo:"thefold-api",trust:"agent",relevance:0.71,accessed:3,age:"5d"},{id:"M-005",content:"Tailwind kan ikke brukes i artifacts — kun pre-defined klasser",type:"general",repo:null,trust:"user",relevance:0.65,accessed:2,age:"10d"},{id:"M-006",content:"pgvector cosine distance: 1 - (a <=> b) for similarity",type:"code_pattern",repo:null,trust:"agent",relevance:0.88,accessed:22,age:"12d"}];
const pats=[{type:"bug_fix",count:12,reused:34},{type:"optimization",count:8,reused:15},{type:"refactoring",count:6,reused:9},{type:"new_feature",count:18,reused:42}];
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Memory</h2><p style={{fontSize:13,color:T.textMuted}}>Semantisk minne med pgvector, temporal decay og kode-mønstre.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"MINNER",v:"142"},{l:"KODE-MØNSTRE",v:"44"},{l:"HYBRID-SØK",v:"60/40",sub:"semantic/keyword"},{l:"DECAY",v:"30d",sub:"halvtid"}].map((s,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",lineHeight:1}}>{s.v}</div>{s.sub&&<div style={{marginTop:4,fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{s.sub}</div>}</div>))}</div></GR>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:20,borderRight:`1px solid ${T.border}`}}><SL>SISTE MINNER</SL>{mems.map((m,i)=>(<div key={i} style={{padding:"10px 0",borderBottom:i<mems.length-1?`1px solid ${T.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><Tag variant={m.type==="error_pattern"?"error":m.type==="decision"?"accent":"default"}>{m.type}</Tag><Tag>{m.trust}</Tag>{m.repo&&<span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{m.repo}</span>}<span style={{fontSize:10,color:T.textFaint,marginLeft:"auto"}}>{m.age}</span></div><div style={{fontSize:12,color:T.textSec,lineHeight:1.5}}>{m.content}</div><div style={{display:"flex",gap:12,marginTop:4}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>relevans: {(m.relevance*100).toFixed(0)}%</span><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>oppslag: {m.accessed}</span></div></div>))}</div>
<div style={{padding:20}}><SL>KODE-MØNSTRE</SL>{pats.map((p,i)=>(<div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 0",borderBottom:i<pats.length-1?`1px solid ${T.border}`:"none"}}><span style={{fontSize:13,color:T.text,fontWeight:500}}>{p.type}</span><div style={{display:"flex",gap:16}}><span style={{fontSize:11,fontFamily:T.mono,color:T.textMuted}}>{p.count} mønstre</span><span style={{fontSize:11,fontFamily:T.mono,color:T.success}}>{p.reused}x gjenbrukt</span></div></div>))}<div style={{marginTop:16,borderTop:`1px solid ${T.border}`,paddingTop:12}}><SL>INTEGRITETSKONTROLL</SL><div style={{display:"flex",gap:12}}><div style={{flex:1,background:T.subtle,padding:"10px 14px",borderRadius:6}}><div style={{fontSize:10,color:T.textMuted}}>SHA-256 HASH</div><div style={{fontSize:14,fontWeight:600,color:T.success}}>OK</div></div><div style={{flex:1,background:T.subtle,padding:"10px 14px",borderRadius:6}}><div style={{fontSize:10,color:T.textMuted}}>SANITERING</div><div style={{fontSize:14,fontWeight:600,color:T.success}}>ASI06</div></div></div></div></div></div></GR><GR mb={40}><div style={{height:1}}/></GR></>);}

// ═══ MONITOR ═══
function MonitorPage(){const checks=[{repo:"thefold-api",type:"dependency_audit",status:"pass",detail:"0 vulnerabilities",time:"03:00"},{repo:"thefold-api",type:"test_coverage",status:"pass",detail:"87% coverage",time:"03:00"},{repo:"thefold-api",type:"code_quality",status:"warn",detail:"3 lint warnings",time:"03:00"},{repo:"thefold-api",type:"doc_freshness",status:"pass",detail:"All docs current",time:"03:00"},{repo:"thefold-frontend",type:"dependency_audit",status:"pass",detail:"0 vulnerabilities",time:"03:00"},{repo:"thefold-frontend",type:"test_coverage",status:"warn",detail:"72% coverage",time:"03:00"},{repo:"thefold-frontend",type:"code_quality",status:"pass",detail:"0 warnings",time:"03:00"},{repo:"thefold-frontend",type:"doc_freshness",status:"fail",detail:"README 14d old",time:"03:00"}];
const healing=[{comp:"AuthMiddleware",score:92,action:"none"},{comp:"ChatBubble",score:78,action:"healed"},{comp:"RateLimiter",score:95,action:"none"},{comp:"FileUploader",score:55,action:"healed"}];
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Monitor & Metrics</h2><p style={{fontSize:13,color:T.textMuted}}>Repo helse-sjekker, healing-pipeline og systemstatus.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"HELSE-SJEKKER",v:checks.length},{l:"BESTÅTT",v:checks.filter(c=>c.status==="pass").length,c:T.success},{l:"ADVARSLER",v:checks.filter(c=>c.status==="warn").length,c:T.warning},{l:"FEILET",v:checks.filter(c=>c.status==="fail").length,c:T.error}].map((s,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:28,fontWeight:600,color:s.c||T.text,letterSpacing:"-0.03em",lineHeight:1}}>{s.v}</div></div>))}</div></GR>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/><div style={{padding:20,borderRight:`1px solid ${T.border}`}}><SL>HELSE-SJEKKER</SL>{checks.map((c,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<checks.length-1?`1px solid ${T.border}`:"none"}}><div style={{width:8,height:8,borderRadius:"50%",background:c.status==="pass"?T.success:c.status==="warn"?T.warning:T.error}}/><span style={{fontSize:11,fontFamily:T.mono,color:T.textFaint,width:140}}>{c.repo}</span><span style={{fontSize:12,color:T.textSec,flex:1}}>{c.type}</span><span style={{fontSize:11,color:T.textMuted}}>{c.detail}</span></div>))}</div>
<div style={{padding:20}}><SL>HEALING PIPELINE</SL>{healing.map((h,i)=>(<div key={i} style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:12,color:T.textSec}}>{h.comp}</span><div style={{display:"flex",gap:8}}><Tag variant={h.action==="healed"?"accent":"default"}>{h.action}</Tag><span style={{fontSize:11,fontFamily:T.mono,color:h.score>=80?T.success:h.score>=60?T.warning:T.error}}>{h.score}/100</span></div></div><div style={{height:6,background:T.subtle,borderRadius:3,overflow:"hidden"}}><div style={{width:`${h.score}%`,height:"100%",background:h.score>=80?T.success:h.score>=60?T.warning:T.error}}/></div></div>))}<div style={{marginTop:16,borderTop:`1px solid ${T.border}`,paddingTop:12}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:10,color:T.textMuted}}>SISTE KJØRING</div><div style={{fontSize:14,fontWeight:600,color:T.text}}>Fredag 03:00</div></div><div><div style={{fontSize:10,color:T.textMuted}}>NESTE</div><div style={{fontSize:14,fontWeight:600,color:T.text}}>om 4d 12t</div></div><Btn sm primary>Kjør nå</Btn></div></div></div></div></GR><GR mb={40}><div style={{height:1}}/></GR></>);}

// ═══ SKILLS ═══
function SkillsPage(){const skills=[{n:"Encore.ts Rules",phase:"inject",scope:"thefold-api",enabled:true,prio:10,tokens:500,confidence:0.94,uses:312,routing:"encore, backend, api"},{n:"TypeScript Strict",phase:"inject",scope:"*",enabled:true,prio:20,tokens:300,confidence:0.91,uses:289,routing:"*.ts, *.tsx"},{n:"Security Awareness",phase:"inject",scope:"*",enabled:true,prio:5,tokens:400,confidence:0.88,uses:156,routing:"auth, security, token"},{n:"Norwegian Docs",phase:"post_run",scope:"*",enabled:false,prio:100,tokens:200,confidence:0.72,uses:45,routing:"documentation"},{n:"Test Coverage",phase:"inject",scope:"*",enabled:false,prio:30,tokens:350,confidence:0.79,uses:78,routing:"test, testing, coverage"},{n:"Project Conventions",phase:"inject",scope:"*",enabled:false,prio:40,tokens:250,confidence:0.65,uses:23,routing:"conventions, style"}];
const[sel,setSel]=useState(null);const sk=sel!==null?skills[sel]:null;
return(<><div style={{paddingTop:40,paddingBottom:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Skills</h2><p style={{fontSize:13,color:T.textMuted}}>Modulært prompt-system med pipeline, routing og scoring.</p></div><Btn primary sm>+ Ny skill</Btn></div></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"AKTIVE",v:skills.filter(s=>s.enabled).length},{l:"PIPELINE-FASER",v:"pre → inject → post"},{l:"TOKEN-BUDSJETT",v:"4 000"}].map((s,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<2?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:20,fontWeight:600,color:T.text}}>{s.v}</div></div>))}</div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:sk?"1fr 1fr":"1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,minHeight:300,position:"relative",overflow:"hidden"}}><PC/><div style={{borderRight:sk?`1px solid ${T.border}`:"none"}}>{skills.map((s,i)=>(<div key={i} onClick={()=>setSel(i===sel?null:i)} style={{padding:"14px 20px",cursor:"pointer",background:sel===i?T.subtle:"transparent",borderBottom:i<skills.length-1?`1px solid ${T.border}`:"none",borderLeft:sel===i?`3px solid ${T.accent}`:"3px solid transparent"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}><span style={{fontSize:13,fontWeight:500,color:T.text}}>{s.n}</span><Tag variant={s.enabled?"success":"default"}>{s.enabled?"aktiv":"av"}</Tag><Tag>{s.phase}</Tag></div><div style={{display:"flex",gap:12}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>prio: {s.prio}</span><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>~{s.tokens} tokens</span><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>confidence: {(s.confidence*100).toFixed(0)}%</span><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{s.uses}x brukt</span></div></div>))}</div>
{sk&&<div style={{padding:24}}><div style={{marginBottom:16}}><div style={{fontSize:18,fontWeight:600,color:T.text,fontFamily:T.brandFont,marginBottom:8}}>{sk.n}</div><div style={{display:"flex",gap:8,marginBottom:16}}><Tag variant={sk.enabled?"success":"default"}>{sk.enabled?"aktiv":"deaktivert"}</Tag><Tag>{sk.phase}</Tag><Tag>{sk.scope}</Tag></div></div>
<SL>DETALJER</SL><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:1,marginBottom:16}}>{[{l:"PRIORITET",v:sk.prio},{l:"TOKEN-ESTIMAT",v:`~${sk.tokens}`},{l:"CONFIDENCE",v:`${(sk.confidence*100).toFixed(0)}%`},{l:"BRUK",v:`${sk.uses}x`}].map((m,i)=>(<div key={i} style={{background:T.subtle,padding:"10px 14px",borderRadius:6}}><div style={{fontSize:10,color:T.textMuted,textTransform:"uppercase",marginBottom:2}}>{m.l}</div><div style={{fontSize:16,fontWeight:600,color:T.text}}>{m.v}</div></div>))}</div>
<SL>ROUTING REGLER</SL><div style={{fontSize:12,fontFamily:T.mono,color:T.textSec,padding:"8px 12px",background:T.subtle,border:`1px solid ${T.border}`,borderRadius:6,marginBottom:16}}>{sk.routing}</div>
<div style={{display:"flex",gap:8}}><Toggle checked={sk.enabled} onChange={()=>{}} label={sk.enabled?"Deaktiver":"Aktiver"}/><Btn sm>Rediger</Btn></div></div>}</div></GR></>);}

// ═══ SANDBOX ═══
function SandboxPage(){const runs=[{id:"SB-001",repo:"thefold-api",mode:"docker",status:"pass",steps:[{n:"typecheck",s:"pass",d:"tsc --noEmit",t:"2.1s"},{n:"lint",s:"pass",d:"eslint --no-error-on-unmatched-pattern",t:"1.4s"},{n:"test",s:"pass",d:"12/12 tests passed",t:"4.8s"},{n:"snapshot",s:"pass",d:"3 files changed",t:"0.2s"},{n:"performance",s:"pass",d:"Build: 1.2s, 42 files",t:"1.3s"}],time:"14m",task:"T-001"},{id:"SB-002",repo:"thefold-frontend",mode:"docker",status:"warn",steps:[{n:"typecheck",s:"pass",d:"tsc --noEmit",t:"3.2s"},{n:"lint",s:"warn",d:"2 warnings",t:"1.8s"},{n:"test",s:"pass",d:"8/8 tests",t:"3.1s"},{n:"snapshot",s:"pass",d:"1 file changed",t:"0.1s"},{n:"performance",s:"pass",d:"Build: 2.4s, 67 files",t:"2.1s"}],time:"1t",task:"T-002"},{id:"SB-003",repo:"thefold-api",mode:"filesystem",status:"fail",steps:[{n:"typecheck",s:"fail",d:"TS2345: Argument type mismatch",t:"1.9s"},{n:"lint",s:"pass",d:"0 warnings",t:"1.2s"},{n:"test",s:"fail",d:"2/12 failed",t:"5.4s"},{n:"snapshot",s:"disabled",d:"Feature flag off"},{n:"performance",s:"disabled",d:"Feature flag off"}],time:"3t",task:"T-003"}];
const[sel,setSel]=useState(null);const sb=sel!==null?runs.find(r=>r.id===sel):null;
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Sandbox</h2><p style={{fontSize:13,color:T.textMuted}}>Isolert kodevalidering — typecheck, lint, test, snapshot, performance.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>{[{l:"KJØRINGER",v:runs.length},{l:"BESTÅTT",v:runs.filter(r=>r.status==="pass").length,c:T.success},{l:"ADVARSLER",v:runs.filter(r=>r.status==="warn").length,c:T.warning},{l:"FEILET",v:runs.filter(r=>r.status==="fail").length,c:T.error}].map((s,i)=>(<div key={i} style={{padding:"18px 20px",borderRight:i<3?`1px solid ${T.border}`:"none"}}><div style={{fontSize:10,fontWeight:500,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{s.l}</div><div style={{fontSize:28,fontWeight:600,color:s.c||T.text,letterSpacing:"-0.03em",lineHeight:1}}>{s.v}</div></div>))}</div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:sb?"1fr 1fr":"1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,minHeight:300,position:"relative",overflow:"hidden"}}><PC/><div style={{borderRight:sb?`1px solid ${T.border}`:"none"}}>{runs.map((r,i)=>(<div key={r.id} onClick={()=>setSel(r.id===sel?null:r.id)} style={{padding:"14px 20px",cursor:"pointer",background:sel===r.id?T.subtle:"transparent",borderBottom:i<runs.length-1?`1px solid ${T.border}`:"none",borderLeft:sel===r.id?`3px solid ${T.accent}`:"3px solid transparent"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{r.id}</span><span style={{fontSize:13,fontWeight:500,color:T.text}}>{r.repo}</span><Tag variant={r.status==="pass"?"success":r.status==="warn"?"accent":"error"}>{r.status}</Tag><Tag>{r.mode}</Tag></div><div style={{display:"flex",gap:12}}><span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>task: {r.task}</span><span style={{fontSize:10,color:T.textFaint,marginLeft:"auto"}}>{r.time}</span></div></div>))}</div>
{sb&&<div style={{padding:24}}><div style={{fontSize:16,fontWeight:600,color:T.text,fontFamily:T.brandFont,marginBottom:4}}>{sb.repo}</div><div style={{display:"flex",gap:8,marginBottom:16}}><Tag variant={sb.status==="pass"?"success":sb.status==="warn"?"accent":"error"}>{sb.status}</Tag><Tag>{sb.mode}</Tag></div><SL>VALIDATION PIPELINE</SL>{sb.steps.map((st,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<sb.steps.length-1?`1px solid ${T.border}`:"none"}}><div style={{width:8,height:8,borderRadius:"50%",background:st.s==="pass"?T.success:st.s==="warn"?T.warning:st.s==="fail"?T.error:T.textFaint}}/><span style={{fontSize:13,fontWeight:500,color:T.text,width:100}}>{st.n}</span><span style={{fontSize:12,color:T.textMuted,flex:1}}>{st.d}</span>{st.t&&<span style={{fontSize:10,fontFamily:T.mono,color:T.textFaint}}>{st.t}</span>}</div>))}</div>}</div></GR></>);}

// ═══ INNSTILLINGER ═══
function InnstillingerPage(){
const[agentOn,setAgentOn]=useState(true);const[subAgOn,setSubAgOn]=useState(false);const[privat,setPrivat]=useState(false);const[notif,setNotif]=useState(true);const[slackNotif,setSlackNotif]=useState(true);const[emailNotif,setEmailNotif]=useState(false);const[autoApprove,setAutoApprove]=useState(false);const[sandboxMode,setSandboxMode]=useState("docker");const[budget,setBudget]=useState("balanced");
return(<><div style={{paddingTop:40,paddingBottom:24}}><h2 style={{fontSize:28,fontWeight:600,color:T.text,letterSpacing:"-0.03em",fontFamily:T.brandFont,marginBottom:8}}>Innstillinger</h2><p style={{fontSize:13,color:T.textMuted}}>Konfigurer agent, varsler, sikkerhet og preferanser.</p></div>
<GR><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderRadius:T.r,position:"relative",overflow:"hidden"}}><PC/>
<div style={{padding:24,borderRight:`1px solid ${T.border}`}}><SL>PROFIL</SL>
<div style={{marginBottom:20}}>{[{l:"Navn",v:"Jørgen André"},{l:"E-post",v:"jorgen@twofold.no"},{l:"Rolle",v:"Admin"},{l:"Organisasjon",v:"Twofold AS"}].map((f,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:i<3?`1px solid ${T.border}`:"none"}}><span style={{fontSize:12,color:T.textMuted}}>{f.l}</span><span style={{fontSize:13,color:T.text,fontWeight:500}}>{f.v}</span></div>))}</div>
<SL>AUTENTISERING</SL>
<div style={{marginBottom:16}}>{[{l:"Auth-metode",v:"OTP via Resend"},{l:"Token-utløp",v:"30 dager"},{l:"Siste innlogging",v:"25. feb 2026, 09:14"}].map((f,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:i<2?`1px solid ${T.border}`:"none"}}><span style={{fontSize:12,color:T.textMuted}}>{f.l}</span><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{f.v}</span></div>))}</div>
<Btn sm>Revoke alle tokens</Btn>
</div>
<div style={{padding:24}}><SL>AGENT-OPPFØRSEL</SL>
<div style={{display:"flex",flexDirection:"column",gap:14,marginBottom:24}}><Toggle checked={agentOn} onChange={setAgentOn} label="Agent-modus"/><Toggle checked={subAgOn} onChange={setSubAgOn} label="Sub-agenter"/><Toggle checked={privat} onChange={setPrivat} label="Privat-modus (inkognito)"/><Toggle checked={autoApprove} onChange={setAutoApprove} label="Auto-godkjenn PRs (kvalitet ≥ 8)"/></div>
<SL>SANDBOX</SL>
<div style={{display:"flex",gap:8,marginBottom:24}}>{["docker","filesystem"].map(m=>(<div key={m} onClick={()=>setSandboxMode(m)} style={{flex:1,padding:"12px 16px",background:sandboxMode===m?T.accentDim:"transparent",border:`1px solid ${sandboxMode===m?T.accent:T.border}`,borderRadius:T.r,cursor:"pointer",transition:"all 0.15s"}}><div style={{fontSize:13,fontWeight:500,color:sandboxMode===m?T.accent:T.text,marginBottom:2}}>{m==="docker"?"Docker":"Filesystem"}</div><div style={{fontSize:10,color:T.textMuted}}>{m==="docker"?"Isolert, --network=none":"Lokal /tmp, for utvikling"}</div></div>))}</div>
<SL>KOSTNADSBUDSJETT</SL>
<div style={{display:"flex",gap:8}}>{[{k:"aggressive_save",l:"Aggressiv",d:"Laveste kostnad"},{k:"balanced",l:"Balansert",d:"Kvalitet/pris"},{k:"quality_first",l:"Kvalitet",d:"Best resultat"}].map(b=>(<div key={b.k} onClick={()=>setBudget(b.k)} style={{flex:1,padding:"12px 16px",background:budget===b.k?T.accentDim:"transparent",border:`1px solid ${budget===b.k?T.accent:T.border}`,borderRadius:T.r,cursor:"pointer",transition:"all 0.15s"}}><div style={{fontSize:13,fontWeight:500,color:budget===b.k?T.accent:T.text,marginBottom:2}}>{b.l}</div><div style={{fontSize:10,color:T.textMuted}}>{b.d}</div></div>))}</div>
</div></div></GR>
<GR mb={40}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",border:`1px solid ${T.border}`,borderTop:"none",borderRadius:`0 0 ${T.r}px ${T.r}px`,position:"relative",overflow:"hidden"}}><PC/>
<div style={{padding:24,borderRight:`1px solid ${T.border}`}}><SL>VARSLER</SL>
<div style={{display:"flex",flexDirection:"column",gap:14}}><Toggle checked={notif} onChange={setNotif} label="Push-varsler"/><Toggle checked={slackNotif} onChange={setSlackNotif} label="Slack-varsler"/><Toggle checked={emailNotif} onChange={setEmailNotif} label="E-postvarsler"/></div>
<div style={{marginTop:20}}><SL>VARSEL-EVENTS</SL>{["task.completed","review.pending","health.alert","agent.error"].map((e,i)=>(<div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 0",borderBottom:i<3?`1px solid ${T.border}`:"none"}}><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{e}</span><Tag variant="success">aktiv</Tag></div>))}</div>
</div>
<div style={{padding:24}}><SL>API & SIKKERHET</SL>
{[{l:"API-nøkkel",v:"thf_••••••••k7x2",a:"Vis"},{l:"Webhook-secret",v:"whsec_••••••••m3p1",a:"Regenerer"},{l:"HMAC-algoritme",v:"SHA-256"},{l:"Rate limit",v:"100 req/min"}].map((f,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:i<3?`1px solid ${T.border}`:"none"}}><span style={{fontSize:12,color:T.textMuted}}>{f.l}</span><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{f.v}</span>{f.a&&<Btn sm>{f.a}</Btn>}</div></div>))}
<div style={{marginTop:20}}><SL>FEATURE FLAGS</SL>{[{f:"MonitorEnabled",v:true},{f:"SandboxAdvancedPipeline",v:true},{f:"MCPRoutingEnabled",v:true},{f:"RegistryExtractionEnabled",v:false},{f:"ZNewMessageContract",v:false}].map((ff,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:i<4?`1px solid ${T.border}`:"none"}}><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{ff.f}</span><Tag variant={ff.v?"success":"default"}>{ff.v?"true":"false"}</Tag></div>))}</div>
</div></div></GR></>);}

// ═══ APP SHELL ═══
export default function App(){const[nav,setNav]=useState("Overview");const[col,setCol]=useState(false);const sw=col?SWC:SW;
const[chatInit,setChatInit]=useState(null);
const startChat=(msg,repo,ghost)=>{setChatInit({msg,repo,ghost});setNav("Chat");};
const ngs=[{items:[{icon:"◉",label:"Overview"}]},{cat:"WORKSPACE",items:[{icon:"◈",label:"Chat",badge:"3"},{icon:"▤",label:"Tasks"},{icon:"⬡",label:"Komponenter"},{icon:"⚡",label:"Skills"}]},{cat:"SYSTEM",items:[{icon:"◎",label:"AI"},{icon:"⬔",label:"Integrasjoner"},{icon:"⊞",label:"MCP"},{icon:"◐",label:"Memory"},{icon:"◫",label:"Monitor"},{icon:"▥",label:"Sandbox"}]}];
const rp=()=>{switch(nav){case"Chat":return <ChatPage initialMsg={chatInit?.msg} initialRepo={chatInit?.repo} initialGhost={chatInit?.ghost}/>;case"Tasks":return <TasksPage/>;case"Komponenter":return <KomponenterPage/>;case"Skills":return <SkillsPage/>;case"AI":return <AIPage/>;case"Integrasjoner":return <IntegrasjonerPage/>;case"MCP":return <MCPPage/>;case"Memory":return <MemoryPage/>;case"Monitor":return <MonitorPage/>;case"Sandbox":return <SandboxPage/>;case"Innstillinger":return <InnstillingerPage/>;default:return <OverviewPage onStartChat={startChat}/>;}};
const useFullWidth=nav==="Chat";

return(<div style={{minHeight:"100vh",background:T.bg,color:T.text,fontFamily:T.sans,display:"flex",justifyContent:"center"}}><style>{`@import url('https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-mono/style.css');@font-face{font-family:'TheFold Brand';src:url('/fonts/thefold.woff2') format('woff2');font-weight:400;font-style:normal;font-display:swap}@font-face{font-family:'Suisse Intl';src:url('/fonts/SuisseIntl-Regular.woff2') format('woff2');font-weight:400;font-style:normal;font-display:swap}@font-face{font-family:'Suisse Intl';src:url('/fonts/SuisseIntl-Medium.woff2') format('woff2');font-weight:500;font-style:normal;font-display:swap}@font-face{font-family:'Suisse Intl';src:url('/fonts/SuisseIntl-SemiBold.woff2') format('woff2');font-weight:600;font-style:normal;font-display:swap}@keyframes spin{to{transform:rotate(360deg)}}@keyframes blink{50%{opacity:0}}@keyframes shimmerMove{0%{background-position:200% 0}100%{background-position:-200% 0}}*{box-sizing:border-box;margin:0;padding:0}body{background:${T.bg}}::selection{background:${T.accentDim};color:${T.accent}}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:${T.border};border-radius:3px}`}</style>
<div style={{width:"100%",maxWidth:sw+CW,minHeight:"100vh",position:"relative",transition:"max-width 0.25s ease"}}>

{/* HEADER */}
<div style={{display:"flex",height:HH,position:"relative",zIndex:2}}><div style={{width:sw,height:HH,borderBottom:`1px solid ${T.border}`,borderRight:`1px solid ${T.border}`,display:"flex",alignItems:"center",gap:col?0:10,padding:col?"0":"0 20px",justifyContent:col?"center":"flex-start",background:T.bg,zIndex:3,transition:"all 0.25s ease",overflow:"hidden"}}><div style={{width:28,height:28,borderRadius:T.r,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,background:`linear-gradient(135deg,${T.accent},${T.brand})`}}><span style={{fontSize:11,fontWeight:800,color:T.bg,fontFamily:T.brandFont}}>TF</span></div>{!col&&<span style={{fontSize:15,fontWeight:600,color:T.text,letterSpacing:"-0.02em",fontFamily:T.brandFont,whiteSpace:"nowrap"}}>TheFold</span>}</div>
<div style={{flex:1,height:HH,borderBottom:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"flex-end",padding:"0 24px",gap:10,background:T.bg,zIndex:2}}>
<Btn sm>Docs</Btn>
<NotifBell onGoTask={(id)=>{setNav("Tasks");}}/>
<div onClick={()=>setNav("Innstillinger")} style={{cursor:"pointer",color:nav==="Innstillinger"?T.accent:T.textMuted,display:"flex",alignItems:"center",padding:6,transition:"color 0.15s"}}><svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M6.86 1.57a1.14 1.14 0 012.28 0c.05.64.75 1 1.28.64a1.14 1.14 0 011.61 1.61c-.36.53-.01 1.23.64 1.28a1.14 1.14 0 010 2.28c-.65.05-1 .75-.64 1.28a1.14 1.14 0 01-1.61 1.61c-.53-.36-1.23-.01-1.28.64a1.14 1.14 0 01-2.28 0c-.05-.65-.75-1-1.28-.64a1.14 1.14 0 01-1.61-1.61c.36-.53.01-1.23-.64-1.28a1.14 1.14 0 010-2.28c.65-.05 1-.75.64-1.28a1.14 1.14 0 011.61-1.61c.53.36 1.23.01 1.28-.64z"/><circle cx="8" cy="8" r="2.5"/></svg></div>
</div></div>

{/* BODY */}
<div style={{display:"flex",minHeight:`calc(100vh - ${HH}px)`,position:"relative"}}>
{/* SIDEBAR */}
<div style={{width:sw,borderRight:`1px solid ${T.border}`,display:"flex",flexDirection:"column",background:T.bg,position:"relative",zIndex:3,transition:"width 0.25s ease",overflow:"hidden"}}>
<div style={{flex:1,padding:col?"16px 4px":"16px 8px",display:"flex",flexDirection:"column",gap:2}}>{ngs.map((g,gi)=>(<div key={gi}>{g.cat&&!col&&<div style={{fontSize:9,fontWeight:600,color:T.textFaint,textTransform:"uppercase",letterSpacing:"0.1em",padding:"12px 14px 4px",fontFamily:T.mono}}>{g.cat}</div>}{g.cat&&col&&<div style={{height:1,background:T.border,margin:"8px 8px"}}/>}{g.items.map(it=>(<div key={it.label} onClick={()=>setNav(it.label)} title={col?it.label:undefined} style={{display:"flex",alignItems:"center",gap:10,padding:col?"9px 0":"9px 14px",justifyContent:col?"center":"flex-start",background:nav===it.label?T.subtle:"transparent",cursor:"pointer",transition:"background 0.12s",position:"relative",minHeight:36}}>{nav===it.label&&<div style={{position:"absolute",left:0,top:"50%",transform:"translateY(-50%)",width:3,height:16,background:T.accent}}/>}<span style={{fontSize:14,color:nav===it.label?T.text:T.textMuted,flexShrink:0}}>{it.icon}</span>{!col&&<span style={{fontSize:13,fontWeight:nav===it.label?500:400,color:nav===it.label?T.text:T.textSec,whiteSpace:"nowrap"}}>{it.label}</span>}{!col&&it.badge&&<span style={{marginLeft:"auto",fontSize:10,fontFamily:T.mono,fontWeight:600,background:T.accentDim,color:T.accent,padding:"1px 6px"}}>{it.badge}</span>}</div>))}</div>))}</div>

<div style={{borderTop:`1px solid ${T.border}`,padding:col?12:16,position:"relative"}}><PC/>{!col&&<><SL>Quick actions</SL><div style={{display:"flex",flexDirection:"column",gap:6}}><Btn sm>⌘K Søk</Btn><Btn sm>⌘N Ny chat</Btn></div></>}{col&&<div style={{display:"flex",justifyContent:"center",color:T.textMuted,fontSize:14}}>⌘</div>}</div>
<div style={{borderTop:`1px solid ${T.border}`,padding:col?12:16,position:"relative"}}><PC/>{!col&&<><SL>Repo-helse</SL>{["thefold-api","thefold-frontend"].map((r,i)=>(<div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"4px 0"}}><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>{r}</span><Tag variant="success">OK</Tag></div>))}</>}{col&&<div style={{display:"flex",justifyContent:"center",color:T.textMuted,fontSize:14}}>◆</div>}</div>
<div style={{borderTop:`1px solid ${T.border}`,padding:col?"12px 8px":"12px 16px",position:"relative"}}><PC/><div style={{display:"flex",alignItems:"center",gap:8,justifyContent:col?"center":"flex-start"}}>{!col&&<div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:500,color:T.text}}>Jørgen André</div><div style={{fontSize:10,color:T.textFaint,fontFamily:T.mono}}>admin</div></div>}{col&&<div style={{width:8,height:8,borderRadius:"50%",background:T.success}}/>}</div></div>
<div style={{borderTop:`1px solid ${T.border}`,padding:col?"12px 8px":"12px 16px",position:"relative"}}><PC/><div onClick={()=>setCol(c=>!c)} style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer",justifyContent:col?"center":"flex-start",color:T.textMuted}}><svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" style={{transform:col?"rotate(180deg)":"rotate(0deg)",transition:"transform 0.25s"}}><path d="M11 2L5 8l6 6"/></svg>{!col&&<span style={{fontSize:12,color:T.textFaint}}>Kollaps</span>}</div></div>
</div>

{/* CONTENT */}
<div style={{flex:1,maxWidth:CW,position:"relative",zIndex:1}}>
{useFullWidth
  ?<div style={{padding:"0 20px"}}>{rp()}</div>
  :<div style={{padding:`0 ${SP}px`,position:"relative"}}><div style={{maxWidth:IW,margin:"0 auto"}}>{rp()}</div></div>
}
</div>
</div></div></div>);
}
